/**
 * Creates an HTML footer for RSS feed items with share link and branding.
 */
export function createShareFooter(shareUrl: string, baseUrl: string): string {
    return `
        <hr style="margin: 20px 0; border-color: #333;"/>
        <p style="color: #888; font-size: 14px;">
            🔗 Share this summary: <a href="${shareUrl}">${shareUrl}</a><br/>
            Generated by <a href="${baseUrl}">TubeSummary</a> AI
        </p>
    `;
}
